// Данные о работах — запасной вариант для открытия без сервера (file://)
const WORKS_DATA = [
  {
    "id": "royal-iris",
    "title": "Royal Iris",
    "title_ru": "Королевский ирис",
    "series": "Botanica",
    "size": "30×40 cm",
    "sqm": 0.12,
    "price_rub": 30000,
    "price_eur": 320,
    "print_price": 1500,
    "year": 2025,
    "materials": "Acrylic, resin, rhinestones, mirror",
    "description": "Ирис — цветок мудрости, надежды и внутренней силы. Его пурпурные лепестки, обрамлённые золотом и кристаллами, несут в себе послание: красота рождается не вопреки сложности, а сквозь неё. Слои рельефа и отражающие поверхности создают живую глубину — работа меняет характер с каждым лучом света, как меняется наше восприятие истины в зависимости от угла зрения. Это приглашение остановиться и увидеть мудрость там, где привычно замечаешь лишь красоту.",
    "description_en": "Royal Iris transforms a floral motif into a jewel-like relief object. Violet petals balanced by mirrored reflections and crystal contours.",
    "image": "royal-iris.jpg",
    "mockup": "royal-iris-interior.jpg",
    "payment_link": "https://yookassa.ru/my/i/acY60NeAkcei/l",
    "available": true,
    "tags": ["botanica", "floral", "purple", "small"]
  },
  {
    "id": "tree-of-wonders",
    "title": "Tree of Wonders",
    "title_ru": "Дерево чудес",
    "series": "Botanica",
    "size": "Ø55 cm",
    "sqm": 0.24,
    "price_rub": 60000,
    "price_eur": 645,
    "print_price": 1500,
    "year": 2025,
    "materials": "Board, resin, stone granules, rhinestones, texture, mirror",
    "description": "Дерево — древнейший символ жизни, роста и связи между мирами. Его корни уходят вглубь земли, а ветви тянутся к свету — так же, как человек соединяет в себе прошлое и устремлённость вперёд. Это напоминание о важности быть укоренённым в своих ценностях и при этом смело тянуться к новому. Золото и кристаллы в работе передают не богатство в привычном смысле, а изобилие внутреннего мира — ту щедрость духа, которая рождается из стойкости и веры в рост.",
    "description_en": "Tree of Wonders is a symbolic statement on growth, abundance and inner resilience. Gold, crystalline texture and mirrored fragments build a luminous surface.",
    "image": "tree-of-wonders.jpg",
    "mockup": "tree-of-wonders-interior.jpg",
    "payment_link": "https://yookassa.ru/my/i/acY7RMUnqGKz/l",
    "available": true,
    "tags": ["botanica", "gold", "round", "medium"]
  },
  {
    "id": "crystal-bloom",
    "title": "Crystal Bloom",
    "title_ru": "Кристальный цветок",
    "series": "Botanica",
    "size": "50×70 cm",
    "sqm": 0.35,
    "price_rub": 87000,
    "price_eur": 935,
    "print_price": 1500,
    "year": 2025,
    "materials": "Resin, texture, acrylic, rhinestones, mirror, stone granules, board",
    "description": "Лотос раскрывается из глубины вод — и в этом движении заключена вся суть духовного пути. Чистота рождается не в отсутствии тьмы, а в способности пройти сквозь неё и всё равно открыться свету. Золотые лепестки и кристальные грани этой работы создают сияющую композицию, которая отражает свет пространства вокруг себя — как душа, достигшая покоя, отражает свет для других. Работа несёт энергию просветления и духовного пробуждения.",
    "description_en": "Crystal Bloom explores softness through structure. Translucent layers, crystalline particles and reflective accents create a luxurious yet calm surface.",
    "image": "crystal-bloom.jpg",
    "mockup": "crystal-bloom-interior.jpg",
    "payment_link": "https://yookassa.ru/my/i/acY9Dg3Yhz_N/l",
    "available": true,
    "tags": ["botanica", "floral", "pink", "medium"]
  },
  {
    "id": "inner-light",
    "title": "Inner Light",
    "title_ru": "Внутренний свет",
    "series": "Relax",
    "size": "Ø40 cm",
    "sqm": 0.13,
    "price_rub": 32000,
    "price_eur": 345,
    "print_price": 1500,
    "year": 2025,
    "materials": "Resin, mirror, gilding, crystal, stone granules",
    "description": "Дзен — это не отрешённость от мира, а полное присутствие в нём. Медитирующая фигура в золоте напоминает: внутренний баланс не достигается усилием — он открывается в тишине. Кристальное сердце в центре — это та точка покоя, к которой мы все возвращаемся сквозь суету. Слоистые текстуры и золотые пигменты создают мерцающую медитативную атмосферу. Работа создана для пространств, где важна гармония — для тех, кто умеет слушать тишину.",
    "description_en": "Inner Light is a meditative circular composition built around centered energy. The crystalline heart acts as the work's emotional anchor.",
    "image": "inner-light.jpg",
    "mockup": "inner-light-interior.jpg",
    "payment_link": "https://yookassa.ru/my/i/acY842J1qGS5/l",
    "available": true,
    "tags": ["relax", "meditation", "gold", "round", "small"]
  },
  {
    "id": "solar-lion",
    "title": "Solar Lion",
    "title_ru": "Солнечный лев",
    "series": "Zoology",
    "size": "50×70 cm",
    "sqm": 0.35,
    "price_rub": 87000,
    "price_eur": 935,
    "print_price": 1500,
    "year": 2025,
    "materials": "Board, texture, resin, acrylic, stones, mirror, gilding, enamel, granules, rhinestones",
    "description": "Огненный лев — архетип лидера, солярный символ мужества и мудрости. Каждая грань его гривы — фрагмент сакральной геометрии: треугольники и пирамиды, собранные в единую структуру, где порядок встречается с первозданной силой огня. Красный — это энергия страсти, трансформации и внутреннего огня. Пирамиды, вплетённые в гриву, словно прокладывают путь от земли к небу — напоминание о стремлении к гармонии и высшему знанию через форму и пропорцию. Эта работа для тех, кто знает: настоящая сила выглядит спокойно.",
    "description_en": "Solar Lion translates strength into a faceted contemporary language. The mane is a sculptural field of reflections and luminous red-gold tones.",
    "image": "solar-lion.jpg",
    "mockup": "solar-lion-interior.jpg",
    "payment_link": "https://yookassa.ru/my/i/acY8uU7Gkx31/l",
    "available": true,
    "tags": ["zoology", "animal", "fire", "gold", "medium"]
  },
  {
    "id": "cosmic-wolf",
    "title": "Cosmic Wolf",
    "title_ru": "Космический волк",
    "series": "Zoology",
    "size": "50×70 cm",
    "sqm": 0.35,
    "price_rub": 87000,
    "price_eur": 935,
    "print_price": 1500,
    "year": 2025,
    "materials": "Board, texture, resin, acrylic, stones, mirror, gilding, enamel, granules, rhinestones",
    "description": "Лунный страж — воплощение интуиции, внутренней силы и тихой мощи инстинкта. Волк, парящий на фоне ночного неба и серпа луны, несёт в себе два начала одновременно: дикий первозданный порыв и созерцательный покой мудреца. Многогранная кристальная структура отражает свет под разными углами — работа меняется в течение дня, как меняется сам лунный цикл. Это напоминание о том, что самые глубокие прозрения приходят не в шуме, а в тишине ночи, когда мы доверяем своему внутреннему компасу.",
    "description_en": "Cosmic Wolf combines crystalline construction with celestial atmosphere. Suspended against a night sky, the figure carries both wild instinct and contemplative stillness.",
    "image": "cosmic-wolf.jpg",
    "mockup": "cosmic-wolf-interior.jpg",
    "payment_link": "https://yookassa.ru/my/i/acY8keLxoyoa/l",
    "available": true,
    "tags": ["zoology", "animal", "night", "silver", "medium"]
  },
  {
    "id": "olive-branch",
    "title": "Olive Branch",
    "title_ru": "Оливковая ветвь",
    "series": "Botanica",
    "size": "70×100 cm",
    "sqm": 0.70,
    "price_rub": 175000,
    "price_eur": 1880,
    "print_price": 1500,
    "year": 2025,
    "materials": "Board, texture, acrylic, mirror, enamel, rhinestones",
    "description": "Оливковое дерево — один из древнейших символов человечества. Долголетие, стойкость, мудрость, изобилие и благословение — всё это вложено в простую ветвь с плодами. Прежде всего это универсальный знак мира: победы духа над конфликтом, примирения с собой и с миром. Мерцающая глубина работы, игра света на рельефной поверхности создают ощущение сияния и просветления — как будто сама ветвь несёт в себе древний свет Средиземноморья. Для пространств, где ценят тишину и смысл.",
    "description_en": "Olive Branch is a study in restraint and finish. Relief droplets, metallic contours and rich green-black tones introduce tactile sophistication.",
    "image": "olive-branch.jpg",
    "mockup": "olive-branch-interior.jpg",
    "payment_link": "https://yookassa.ru/my/i/acY8bsnNmTVE/l",
    "available": true,
    "tags": ["botanica", "nature", "green", "large"]
  },
  {
    "id": "wings-of-light",
    "title": "Wings of Light",
    "title_ru": "Крылья света",
    "series": "Zoology",
    "size": "70×100 cm",
    "sqm": 0.70,
    "price_rub": 175000,
    "price_eur": 1880,
    "print_price": 1500,
    "year": 2025,
    "materials": "Board, mirror, enamel, rhinestones",
    "description": "Перо — символ свободы, лёгкости и духовной связи с высшим. В разных традициях перья означали послание от мира иного, знак присутствия и защиты. Эта работа сводит мотив пера к его сути — ритму, свету и движению. Золото и серебро создают утончённый контраст, а чистый фон даёт пространству дышать. Декоративный рельеф наполняет поверхность глубиной и блеском, превращая работу в медитацию на тему лёгкости — того состояния, когда внутренняя свобода становится видимой.",
    "description_en": "Wings of Light reduces the feather motif to rhythm, light and movement. Gold and silver tones create a refined contrast on a clean background.",
    "image": "wings-of-light.jpg",
    "mockup": "wings-of-light-interior.jpg",
    "payment_link": "https://yookassa.ru/my/i/acY8NpLnW5tv/l",
    "available": true,
    "tags": ["zoology", "feathers", "gold", "silver", "large"]
  },
  {
    "id": "golden-leopard",
    "title": "Golden Leopard",
    "title_ru": "Золотой леопард",
    "series": "Zoology",
    "size": "50×70 cm",
    "sqm": 0.35,
    "price_rub": 87000,
    "price_eur": 935,
    "print_price": 1500,
    "year": 2026,
    "materials": "Board, texture, acrylic, resin, preserved moss",
    "description": "Леопард — символ интуиции, внутренней силы и тихой мощи. Он не демонстрирует силу — он её воплощает. Выступая из скульптурных ветвей на фоне золотого пространства, этот зверь кажется одновременно загадочным и величественным. Бирюзовые глаза контрастируют с тёплым золотом, даруя работе ощущение живого присутствия. Многослойный рельеф, ручная роспись и декоративные элементы создают глубину и динамику. Каждая деталь создана вручную — и именно это делает каждое произведение неповторимым артефактом.",
    "description_en": "Golden Leopard merges portrait, landscape and material relief. The gilded background lifts the animal from narrative into icon.",
    "image": "golden-leopard.jpg",
    "mockup": "golden-leopard-interior.jpg",
    "payment_link": "https://yookassa.ru/my/i/acY8Bhi9B68T/l",
    "available": true,
    "tags": ["zoology", "animal", "gold", "nature", "medium"]
  },
  {
    "id": "golden-eagle",
    "title": "Golden Eagle",
    "title_ru": "Золотой орёл",
    "series": "Zoology",
    "size": "50×70 cm",
    "sqm": 0.35,
    "price_rub": 87000,
    "price_eur": 935,
    "print_price": 1500,
    "year": 2026,
    "materials": "Board, mirror, rhinestones, resin, acrylic, texture, enamel",
    "description": "Перед вами — картина о встрече неба и земли, о том моменте, когда сила становится благородной, а полёт обретает смысл. Золотые перья — как отпечаток солнечной воли, символ изобилия, мужества и внутреннего света. Распахнутые крылья — не просто стремление вверх, а готовность взять ответственность, защитить и поддержать. Точность взгляда орла — это прозорливость, способность видеть суть сквозь сумятицу и выбирать путь. Лучи света — знак вдохновения и наставления. Эта работа задаёт вопрос: где в вашей жизни требуется ясность взгляда, а где — смелость расправить крылья?",
    "description_en": "Golden Eagle captures the decisive moment of descent. Wings, plumage and reflected light are orchestrated into a sculptural image of focus and freedom.",
    "image": "golden-eagle.jpg",
    "mockup": "golden-eagle-interior.jpg",
    "payment_link": "https://yookassa.ru/my/i/acY7yfq_TsGS/l",
    "available": true,
    "tags": ["zoology", "animal", "gold", "freedom", "medium"]
  },
  {
    "id": "body-of-light",
    "title": "Body of Light",
    "title_ru": "Тело света",
    "series": "Abstraction",
    "size": "50×70 cm",
    "sqm": 0.35,
    "price_rub": 150000,
    "price_eur": 1615,
    "print_price": 1500,
    "year": 2025,
    "materials": "Board, texture, resin, acrylic, rhinestones",
    "description": "Свет — это не украшение. Это структура. Форма хранит тишину. Геометрия хранит замысел. Материя обретает присутствие. Этот объект создан не для того, чтобы освещать пространство — он создан, чтобы его очертить. Круговая рельефная форма на сдержанном фоне превращает абстрактный узор в ощущение сконцентрированной энергии — точки, где видимое и невидимое встречаются. Сакральное архитектурное искусство для тех, кто чувствует пространство не глазами, а всем существом.",
    "description_en": "Body of Light is the most architectural work in the portfolio. A circular relief form transforms abstract pattern into the sense of a concentrated energetic core.",
    "image": "body-of-light.jpg",
    "mockup": "body-of-light-interior.jpg",
    "payment_link": "https://yookassa.ru/my/i/acY7bKUM3hnb/l",
    "available": true,
    "tags": ["abstraction", "architecture", "white", "silver", "medium"]
  },
  {
    "id": "golden-peacock",
    "title": "Golden Peacock",
    "title_ru": "Золотой павлин",
    "series": "Zoology",
    "size": "60×80 cm",
    "sqm": 0.48,
    "price_rub": 200000,
    "price_eur": 2150,
    "print_price": 1500,
    "year": 2025,
    "materials": "Resin, board, texture, acrylic, rhinestones, mirror, enamels, gilding",
    "description": "Императорский павлин — воплощение красоты, элегантности и сияния внутренней силы. В восточной традиции он символизирует бессмертие, мудрость и способность трансформировать яд в исцеление — принимать тьму и обращать её в свет. Скульптурная поверхность улавливает и отражает свет, усиливая витиеватые детали павлина и окружающих ботанических элементов. Работа сочетает орнаментальное богатство с современной геометрической структурой — это не декор, это манифест красоты как силы. Главная работа коллекции.",
    "description_en": "Golden Peacock is conceived as a hero piece. Luminous plumage, gilded structure and floral environment create a regal image with immediate decorative impact.",
    "image": "golden-peacock.jpg",
    "mockup": "golden-peacock-interior.jpg",
    "payment_link": "https://yookassa.ru/my/i/acWmeN3116-8/l",
    "available": true,
    "tags": ["zoology", "animal", "gold", "hero", "large"]
  }
];
